# Basic Site Settings
locale                   : "en-US"
title                    : "Arian Afshar's Academic Homepage"
title_separator          : "-"
name                     : &name "Arian Afshar"
description              : &description "Physics Student with Interests in Quantum Theory, General Relativity, and Statistical Physics"
url                      : https://arian-afr.github.io/arian.afr.github.io/
baseurl                  : "" 
repository               : "arian-afr.github.io/arian.afr.github.io"

# Site Author
author:
  avatar           : "profile2.png"
  name             : "Arian Afshar"
  pronouns         :  
  bio              : "Physics student at Sharif University of Technology with a strong background in Quantum Theory, General Relativity, and Statistical Physics."
  location         : "Tehran, Iran"
  employer         : "Sharif University of Technology"
  uri              : 
  email            : "arian.afr@yahoo.com" 

  # Academic websites
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : 
  orcid            : "http://orcid.org/yourorcidurl" 
  semantic         : 
  pubmed           : 
  researchgate     : 

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "arian-afr"
  kaggle           :   
  stackoverflow    :    

  # Social media
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "arian-afshar-581681203"
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Conference Papers
publications:
  - title: "Graph Theoretical Approach to Vicsek Model"
    authors: "A. Afshar, F. Abbsian, S. Rouhani"
    conference: "ECSPP 2024"
    year: 2024
    url: # Add URL if available

# Projects
projects:
  - title: "A Generic Topological Criterion for Flat Bands in Two Dimensions"
    institution: "Karlsruhe Institute of Technology (KIT)"
    supervisor: "Prof. Jörg Schimalian"
    date: "Apr 2024 - Present"
    description: "This project focuses on deriving a topological criterion for flat bands in two-dimensional systems."

  - title: "Flow of Information"
    institution: "Shahid Beheshti University"
    supervisor: "Prof. Reza Jafari"
    date: "Nov 2022 – Jun 2023"
    description: "Studied the flow of information in complex systems under various conditions."

  - title: "Phase Transition in Vicsek Model"
    institution: "Sharif University of Technology (SUT)"
    supervisor: "Prof. Shahin Rouhani"
    date: "Sep 2023 – Present"
    description: "Analyzed phase transitions within the Vicsek model, focusing on collective motion."

  - title: "Calculating Adsorption Energy DFT"
    institution: "Isfahan University of Technology"
    supervisor: "Prof. Ali Hashemifar"
    date: "Jul 2023 – Aug 2023"
    description: "Calculated adsorption energy using Density Functional Theory (DFT)."

# Experience
experience:
  - title: "Manager of the Translation Group"
    institution: "Sharif University of Technology"
    role: "Manager"
    date: # Add relevant date if available
    description: "Managed a group responsible for translating academic materials."

  - title: "Department Library Manager"
    institution: "Sharif University of Technology"
    role: "Manager"
    date: # Add relevant date if available
    description: "Oversaw the operations and management of the department's library."

  - title: "Teaching Assistant for Intro to General Relativity"
    institution: "Sharif University of Technology"
    supervisor: "Dr. Sohrab Rahvar"
    date: # Add relevant date if available
    description: "Assisted in teaching the course 'Intro to General Relativity' for undergraduate and graduate students."

  - title: "Teaching Assistant for Electromagnetism 1 & 2"
    institution: "Sharif University of Technology"
    supervisor: "Dr. Shant Baghram"
    date: # Add relevant date if available
    description: "Assisted in teaching 'Electromagnetism 1 & 2' courses twice."

  - title: "Teaching Assistant for Experimental Methods in Physics"
    institution: "Sharif University of Technology"
    supervisor: "Dr. Alireza Moshfegh"
    date: # Add relevant date if available
    description: "Assisted in teaching 'Experimental Methods in Physics' for undergraduate and graduate students."

# Awards
awards:
  - title: "Top 0.3% in 2020 University Entrance Exam (Physics and Mathematics)"
    date: 2020
    description: "Ranked among the top 0.3% in the national university entrance exam for Physics and Mathematics."

  - title: "Top 0.8% in 2020 University Entrance Exam (Foreign Languages: English)"
    date: 2020
    description: "Ranked among the top 0.8% in the national university entrance exam for Foreign Languages: English."

  - title: "Ranked Second Among 61 Students"
    date: # Add relevant date if available
    description: "Ranked second in class for four consecutive years."

# Summer Schools and Internships
summer_schools:
  - title: "New Horizons in Physics"
    institution: "Isfahan University of Technology"
    date: # Add relevant date if available
    description: "Participated in the 'New Horizons in Physics' summer school."

  - title: "Introduction to Complex Systems"
    institution: "Utrecht University"
    date: # Add relevant date if available
    description: "Attended the 'Introduction to Complex Systems' summer school."

# Site Settings
teaser                   :  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false 
comments:
  provider               : 
  disqus:
    shortname            :
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" 
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" 

atom_feed:
  hide                   : false     
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  

# For specifying social profiles
social:
  type                   : 
  name                   : 
  links: 

# Analytics
analytics:
  provider               :  "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
